name: dotnet Build

on:
  push:
    branches:
    - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.1]
        steps:

        - uses: actions/checkout@main
        - uses: actions/setup-dotnet@v1
            with:
                dotnet-version: '3.1.1'

        - run: dotnet build awesomeproject
